name: Run Postman Collection

on:
  push:
    branches:
      - main  # Adjust to your main branch name

jobs:
  run_postman_collection:
    runs-on: ubuntu-latest  # Use the desired runner environment
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14  # Use the desired Node.js version
        
      - name: Install dependencies
        run: npm install -g newman  # Install Newman globally
      
      - name: Run Postman Collection
        run: newman run Booking_Api.postman_collection.json

      - name: Install Reporter htmlextra
        run:  npm install -g newman-reporter-htmlextra

      - name: Run Postman Collection with Reporter htmlextra
        run: newman run Booking_Api.postman_collection.json -r htmlextra
      - name: Move HTML Report
        run: mv newman/*.html reports/
        working-directory: PostMan  # Specify the directory where the report should be moved

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add reports/*.html
          git commit -m "Add Newman HTML report"
          git push
        working-directory: PostMan
