name: Run Postman Collection

on:
  push:
    branches:
      - main  # Adjust to your main branch name

jobs:
  run_postman_collection:
    runs-on: ubuntu-latest  # Use the desired runner environment
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # - name: Create dir
      #   run: |
      #     mkdir TestArtifacts
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14  # Use the desired Node.js version
        
      - name: Install dependencies
        run: |
         npm install -g newman  # Install Newman globally
         npm install -g newman-reporter-slackreporter
         npm install -g newman-reporter-htmlextra
        
      
      - name: Run Postman Collection
        run: |
          dir
          newman run Booking_Api.postman_collection.json -r htmlextra cli,json,html --reporter-htmlextra-export htmlreport.html
          dir

      # - name: Change dir
      #   run: |
      #     cd TestArtifacts
      #     dir

     # Upload the reports to htmlreport.html which is in the root file
      - name: Output the result
        uses: actions/upload-artifact@v2
        with:
          name: Reports
          path: htmlreport.html
          # if-no-files-found: error
     
       
