---
name: Newman Cli
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: null
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: create dir
        run: |
          mkdir sampleArtifact
      - name: Install Node
      - uses: actions/checkout@v3
        with:
          node-version: 17.x
      - name: Install newman
        run: |
          npm install -g newman
      - name: run collection
        run: |
          newman run Booking_Api.postman_collection.json
      - name: Publish Report
      - uses: actions/upload-artifact@v3
        with:
          Name: Sample Report
          Path: SampleArtifact
